tasks:
  - init: ./mvnw clean install -f backend/pom.xml  # Install backend dependencies
  - command: java -jar /workspace/backend/target/taskone-0.0.1-SNAPSHOT.jar # Start Spring Boot

ports:
  - port: 8080 # Spring Boot